spring.application.name=user-service

server.port=9020

spring.datasource.url=jdbc:postgresql://localhost:5432/usersDB
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=create-drop
